
import React, { useState } from 'react';
import { Contact, DocumentTemplate } from '../types';
import { FileText, Sparkles, Save, Download, Copy, RefreshCw, ChevronRight, User, Shield, Gavel, Zap, MessageSquare, Fingerprint, Mail, Smartphone } from 'lucide-react';
import * as geminiService from '../services/geminiService';
import { useAuth } from '../contexts/AuthContext';
import { supabase } from '../lib/supabaseClient';
import { resolveTenantIdForUser } from '../utils/tenantContext';
import RequiredDisclaimers from './legal/RequiredDisclaimers';

interface DocumentGeneratorProps {
  contacts: Contact[];
  onUpdateContact: (contact: Contact) => void;
}

const TEMPLATES: DocumentTemplate[] = [
  {
    id: 'tpl_omnibus',
    name: 'Master Service Agreement v2.5',
    category: 'Legal',
    variables: ['Company', 'Contact_Name', 'Date', 'Agency_Name'],
    content: `MASTER SERVICE & INTELLIGENCE AGREEMENT\n\nThis agreement is made as of {{Date}} between {{Agency_Name}} ("Provider") and {{Company}} ("Client").\n\n1. SCOPE OF AI ADVISORY\nProvider utilizes the Nexus Neural Core to analyze Client data. Client acknowledges that AI-generated "Battle Cards" and "Credit Memos" are strategic models and do not constitute a final credit decision.\n\n2. NEURAL FORENSIC CONSENT\nClient expressly authorizes Provider to perform binary and metadata forensic audits on all uploaded financial documents to verify authenticity and detect digital tampering.\n\n3. BIOMETRIC IDENTITY LINK\nClient agrees to utilize the Biometric Identity Link protocol (Facial Audit) to secure the capital transmission path. Biometric hashes are encrypted and used solely for identity verification.\n\n4. SUCCESS FEES\nClient agrees to a success fee of 10% for all liquidity events originated via Provider's lender marketplace.`
  },
  {
    id: 'tpl_marketing_consent',
    name: 'Automated Outreach Authorization',
    category: 'Legal',
    variables: ['Company', 'Contact_Name', 'Date', 'Email'],
    content: `COMMUNICATION PROTOCOL AUTHORIZATION\n\nClient: {{Company}}\nEmail: {{Email}}\n\n1. DRIP CAMPAIGN CONSENT\nBy executing this document, Client provides express written consent to receive automated educational and marketing email sequences ("Drip Campaigns") generated by Nexus AI. \n\n2. DATA ENRICHMENT\nClient authorizes Provider to utilize third-party data enrichment tools (LinkedIn, Google News) to tailor communication content to Client's specific industry and revenue magnitude.\n\n3. OPT-OUT\nClient may revoke this authorization at any time via the "Communication Settings" in the Client Portal.`
  },
  {
    id: 'tpl_nda',
    name: 'Mutual NDA (Encrypted)',
    category: 'Legal',
    variables: ['Company', 'Contact_Name', 'Date'],
    content: `MUTUAL NON-DISCLOSURE AGREEMENT\n\nThis Agreement covers the exchange of sensitive bank spreading data and proprietary underwriting models between Nexus and {{Company}}.\n\nAll data transmitted is protected via AES-256 encryption. Neural transcripts from sales calls are handled in accordance with Provider's Data Privacy Protocol...`
  },
  {
    id: 'tpl_joint_venture',
    name: 'Partner Participation Agreement',
    category: 'Contract',
    variables: ['Partner_Name', 'Split_Percentage', 'Date'],
    content: `PARTNER NODE AGREEMENT\n\nThis agreement establishes {{Partner_Name}} as a verified Node in the Nexus Ecosystem.\n\n1. REVENUE SHARE\nPartner shall receive {{Split_Percentage}}% of net success fees for all attributed entities.\n\n2. AI TOOL ACCESS\nPartner is granted access to the Content Factory and Lead Discovery Map for use in originating qualified business leads.`
  }
];

const DocumentGenerator: React.FC<DocumentGeneratorProps> = ({ contacts, onUpdateContact }) => {
  const [selectedContactId, setSelectedContactId] = useState<string>('');
  const [selectedTemplate, setSelectedTemplate] = useState<DocumentTemplate | null>(null);
  const [documentContent, setDocumentContent] = useState('');
  const [variables, setVariables] = useState<Record<string, string>>({});
  const [aiPrompt, setAiPrompt] = useState('');
  const [isGeneratingDisclosure, setIsGeneratingDisclosure] = useState(false);
  const [isNeuralEditing, setIsNeuralEditing] = useState(false);
  const [isRequestingApproval, setIsRequestingApproval] = useState(false);
  const { user } = useAuth();

  const selectedContact = contacts.find(c => c.id === selectedContactId);

  const handleTemplateSelect = (template: DocumentTemplate) => {
    setSelectedTemplate(template);
    setDocumentContent(template.content);
    
    if (selectedContact) {
      const newVars: Record<string, string> = {};
      template.variables.forEach(v => {
        if (v === 'Company') newVars[v] = selectedContact.company;
        if (v === 'Contact_Name') newVars[v] = selectedContact.name;
        if (v === 'Email') newVars[v] = selectedContact.email;
        if (v === 'Agency_Name') newVars[v] = 'Nexus Financial';
        if (v === 'Partner_Name') newVars[v] = 'Strategic Partner';
        if (v === 'Date') newVars[v] = new Date().toLocaleDateString();
        if (v === 'Split_Percentage') newVars[v] = '50';
      });
      setVariables(newVars);
      updatePreview(template.content, newVars);
    } else {
        setVariables({});
    }
  };

  const updatePreview = (content: string, vars: Record<string, string>) => {
    let text = content;
    Object.entries(vars).forEach(([key, val]) => {
      text = text.replace(new RegExp(`{{${key}}}`, 'g'), val);
    });
    setDocumentContent(text);
  };

  const handleVariableChange = (key: string, val: string) => {
    const newVars = { ...variables, [key]: val };
    setVariables(newVars);
    if (selectedTemplate) {
        let text = selectedTemplate.content;
        Object.entries(newVars).forEach(([k, v]) => {
            text = text.replace(new RegExp(`{{${k}}}`, 'g'), v);
        });
        setDocumentContent(text);
    }
  };

  const handleNeuralEdit = async () => {
    if (!aiPrompt || !documentContent) return;
    setIsNeuralEditing(true);
    try {
        const revised = await geminiService.generateContractAmendment(documentContent, aiPrompt);
        setDocumentContent(revised);
        setAiPrompt('');
    } finally {
        setIsNeuralEditing(false);
    }
  };

  const handleAddDisclosure = async () => {
    setIsGeneratingDisclosure(true);
    try {
        const jurisdiction = selectedContact?.businessProfile?.state || 'California';
        const disclosure = await geminiService.generateLegalDisclosure(
            selectedTemplate?.name || 'Standard Agreement',
            jurisdiction,
            { company: selectedContact?.company }
        );
        setDocumentContent(prev => prev + "\n\n--- JURISDICTIONAL COMPLIANCE ("+jurisdiction+") ---\n" + disclosure);
    } finally {
        setIsGeneratingDisclosure(false);
    }
  };

  const handleRequestClientApproval = async () => {
    if (!selectedContact) { alert("Please select a contact first."); return; }
    if (!documentContent.trim()) { alert("Document content is empty."); return; }
    if (!user?.id) { alert("Sign in required."); return; }

    if (!selectedContact.email) {
      alert("Selected contact is missing an email. Client approval requires an approver email.");
      return;
    }

    setIsRequestingApproval(true);
    try {
      const tenantId = await resolveTenantIdForUser(user.id);
      if (!tenantId) throw new Error('No tenant context found for current user.');

      const packetTitle = `${selectedContact.company} - ${selectedTemplate?.name || 'Dispute Package'}`;
      const { data: packet, error: packetError } = await supabase
        .from('dispute_mail_packets')
        .insert({
          tenant_id: tenantId,
          requester_user_id: user.id,
          approver_email: selectedContact.email,
          contact_id: selectedContact.id,
          contact_name: selectedContact.name,
          contact_email: selectedContact.email,
          packet_title: packetTitle,
          document_name: `${selectedTemplate?.name || 'Document'}.txt`,
          document_body: documentContent,
          status: 'pending_client_approval',
          provider: 'docupost',
        })
        .select('id')
        .single();

      if (packetError || !packet?.id) {
        throw new Error(packetError?.message || 'Unable to create mailing approval packet.');
      }

      await supabase.from('dispute_mail_events').insert({
        packet_id: packet.id,
        tenant_id: tenantId,
        actor_user_id: user.id,
        event_type: 'mail_packet.approval_requested',
        metadata: {
          approver_email: selectedContact.email,
          contact_name: selectedContact.name,
        },
      });

      await supabase.from('audit_events').insert({
        tenant_id: tenantId,
        actor_user_id: user.id,
        event_type: 'mail_packet.approval_requested',
        metadata: {
          packet_id: packet.id,
          approver_email: selectedContact.email,
        },
      });

      alert(`Client approval requested from ${selectedContact.email}. Packet is now pending client approval.`);
    } catch (e: any) {
      alert(e?.message || 'Failed to request client approval.');
    } finally {
      setIsRequestingApproval(false);
    }
  };

  const handleSaveToVault = () => {
    if (!selectedContact) { alert("Please select a contact first."); return; }
    const blob = new Blob([documentContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const newDoc = {
        id: `doc_gen_${Date.now()}`,
        name: `${selectedTemplate?.name || 'Document'} - ${new Date().toISOString().split('T')[0]}.txt`,
        type: 'Legal' as const,
        status: 'Pending Review' as const,
        uploadDate: new Date().toLocaleDateString(),
        fileUrl: url
    };
    onUpdateContact({
        ...selectedContact,
        documents: [...(selectedContact.documents || []), newDoc],
        activities: [...(selectedContact.activities || []), {
            id: `act_gen_${Date.now()}`,
            type: 'system',
            description: `Drafted updated agreement: ${newDoc.name}`,
            date: new Date().toLocaleString(),
            user: 'Admin'
        }]
    });
    alert("Document pushed to Subject Vault for review.");
  };

  return (
    <div className="h-[calc(100vh-100px)] flex flex-col md:flex-row gap-6 animate-fade-in">
      
      <div className="w-full md:w-80 flex flex-col gap-6 bg-white border border-slate-200 rounded-[2rem] p-6 shadow-sm overflow-y-auto">
         <RequiredDisclaimers title="Dispute Workflow Disclaimers" />
         <div>
            <label className="block text-[10px] font-black text-slate-500 uppercase mb-4 tracking-widest px-2">1. Select Subject</label>
            <div className="relative">
                <User className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={16} />
                <select 
                    value={selectedContactId} 
                    onChange={(e) => setSelectedContactId(e.target.value)}
                    className="w-full pl-10 pr-4 py-3 bg-slate-50 border border-slate-200 rounded-xl text-xs font-bold focus:ring-2 focus:ring-blue-500 outline-none appearance-none"
                >
                    <option value="">-- Choose Subject --</option>
                    {contacts.map(c => <option key={c.id} value={c.id}>{c.company} ({c.name})</option>)}
                </select>
            </div>
         </div>

         <div>
            <label className="block text-[10px] font-black text-slate-500 uppercase mb-4 tracking-widest px-2">2. Intelligence Template</label>
            <div className="space-y-2">
                {TEMPLATES.map(tpl => (
                    <button 
                        key={tpl.id}
                        onClick={() => handleTemplateSelect(tpl)}
                        className={`w-full text-left px-5 py-4 rounded-xl text-xs font-black uppercase tracking-tight border-2 transition-all flex justify-between items-center ${
                            selectedTemplate?.id === tpl.id 
                            ? 'bg-blue-600 border-blue-600 text-white shadow-lg' 
                            : 'bg-white border-slate-100 text-slate-500 hover:border-blue-300'
                        }`}
                    >
                        {tpl.name}
                        {selectedTemplate?.id === tpl.id && <ChevronRight size={14} />}
                    </button>
                ))}
            </div>
         </div>

         {selectedTemplate && (
             <div className="animate-fade-in">
                 <label className="block text-[10px] font-black text-slate-500 uppercase mb-4 tracking-widest px-2">3. Protocol Variables</label>
                 <div className="space-y-4">
                     {selectedTemplate.variables.map(v => (
                         <div key={v}>
                             <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest ml-1 mb-1.5 block">{v.replace('_', ' ')}</label>
                             <input 
                                type="text" 
                                value={variables[v] || ''}
                                onChange={(e) => handleVariableChange(v, e.target.value)}
                                className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs font-bold focus:border-blue-500 outline-none transition-colors shadow-inner"
                             />
                         </div>
                     ))}
                 </div>
             </div>
         )}
      </div>

      <div className="flex-1 flex flex-col bg-white border border-slate-200 rounded-[2.5rem] shadow-sm overflow-hidden relative">
         <div className="p-6 border-b border-slate-100 bg-slate-50/50 flex justify-between items-center">
             <h2 className="font-black text-sm text-slate-800 flex items-center gap-3 uppercase tracking-tighter">
                 <Gavel size={20} className="text-blue-600" /> 
                 {selectedTemplate ? selectedTemplate.name : 'Legal Protocol Draftsman'}
             </h2>
             <div className="flex gap-2">
                 <button onClick={handleAddDisclosure} disabled={!selectedTemplate || isGeneratingDisclosure} className="text-[9px] font-black uppercase tracking-widest px-4 py-2 rounded-xl border-2 border-indigo-100 text-indigo-600 hover:bg-indigo-50 flex items-center gap-2 transition-all">
                    {isGeneratingDisclosure ? <RefreshCw className="animate-spin" size={12}/> : <Shield size={12}/>}
                    Inject Disclosure
                 </button>
                 <button onClick={() => navigator.clipboard.writeText(documentContent)} className="p-2 text-slate-400 hover:bg-slate-200 rounded-xl transition-all"><Copy size={18}/></button>
                 <button className="p-2 text-slate-400 hover:bg-slate-200 rounded-xl transition-all"><Download size={18}/></button>
             </div>
         </div>
         <textarea 
            value={documentContent}
            onChange={(e) => setDocumentContent(e.target.value)}
            className="flex-1 p-10 text-sm font-mono leading-relaxed resize-none outline-none text-slate-700 bg-slate-50/10 custom-scrollbar"
            placeholder="Select a protocol template to begin synthesis..."
         />
         <div className="p-6 border-t border-slate-100 flex justify-end gap-3">
             <button
                onClick={handleRequestClientApproval}
                disabled={!selectedContact || !documentContent || isRequestingApproval}
                className="border-2 border-cyan-200 text-cyan-700 px-6 py-4 rounded-2xl font-black uppercase text-[10px] tracking-[0.16em] hover:bg-cyan-50 flex items-center gap-3 disabled:opacity-50 transition-all"
             >
                {isRequestingApproval ? <RefreshCw className="animate-spin" size={16} /> : <MessageSquare size={16} />}
                {isRequestingApproval ? 'Requesting Approval...' : 'Request Client Approval'}
             </button>
             <button 
                onClick={handleSaveToVault}
                disabled={!selectedContact || !documentContent}
                className="bg-slate-950 text-white px-10 py-4 rounded-2xl font-black uppercase text-[10px] tracking-[0.2em] hover:bg-blue-600 flex items-center gap-3 disabled:opacity-50 shadow-2xl active:scale-95 transition-all"
             >
                 <Save size={18} /> Push to Subject Vault
             </button>
         </div>
      </div>

      <div className="w-full md:w-80 bg-slate-900 rounded-[2.5rem] p-8 flex flex-col shadow-2xl relative overflow-hidden">
          <div className="absolute top-0 right-0 p-4 opacity-5"><Zap size={140} className="text-blue-400" /></div>
          
          <div className="mb-8 relative z-10">
              <h3 className="font-black text-blue-400 flex items-center gap-2 uppercase tracking-widest text-xs"><Sparkles size={18} /> Neural Clause Editor</h3>
              <p className="text-[10px] text-slate-500 font-bold uppercase mt-2 leading-relaxed">Update your contracts using natural language directives.</p>
          </div>
          
          <div className="flex-1 flex flex-col gap-4 relative z-10">
              <textarea 
                value={aiPrompt}
                onChange={(e) => setAiPrompt(e.target.value)}
                placeholder="e.g. Add a 3-day rescission period for Florida merchants."
                className="flex-1 w-full p-4 bg-white/5 border border-white/10 rounded-2xl text-xs font-medium text-slate-300 focus:ring-2 focus:ring-blue-500 outline-none resize-none shadow-inner"
              />
              <button 
                onClick={handleNeuralEdit}
                disabled={isNeuralEditing || !aiPrompt || !documentContent}
                className="bg-blue-600 text-white py-4 rounded-2xl font-black uppercase text-[10px] tracking-widest hover:bg-blue-500 flex items-center justify-center gap-2 transition-all shadow-xl disabled:opacity-50 active:scale-95"
              >
                  {isNeuralEditing ? <RefreshCw className="animate-spin" size={16} /> : <Zap size={16} />}
                  {isNeuralEditing ? 'Processing...' : 'Apply Neural Edit'}
              </button>
          </div>

          <div className="mt-8 pt-8 border-t border-white/5 relative z-10">
              <p className="text-[9px] font-black text-slate-500 uppercase tracking-widest mb-4">Quick Protocols</p>
              <div className="grid grid-cols-1 gap-2">
                  <button onClick={() => setAiPrompt("Inject the standard CAN-SPAM opt-in disclosure for email marketing.")} className="text-left text-[9px] font-black uppercase tracking-widest text-slate-400 hover:text-white flex items-center gap-2 transition-colors"><Mail size={12}/> Marketing Opt-In</button>
                  <button onClick={() => setAiPrompt("Add the Biometric Identity verification disclaimer.")} className="text-left text-[9px] font-black uppercase tracking-widest text-slate-400 hover:text-white flex items-center gap-2 transition-colors"><Fingerprint size={12}/> Biometric Clause</button>
                  <button onClick={() => setAiPrompt("Add the FCRA disclosure regarding automated credit pulls.")} className="text-left text-[9px] font-black uppercase tracking-widest text-slate-400 hover:text-white flex items-center gap-2 transition-colors"><Shield size={12}/> FCRA Disclosure</button>
              </div>
          </div>
      </div>

    </div>
  );
};

export default DocumentGenerator;
