export const ALL_PERMISSIONS = '*';

export const PERMISSION_LIST = [
  'inbox.read',
  'inbox.write',
  'contacts.read',
  'contacts.write',
  'contacts.merge',
  'routing.read',
  'routing.manage',
  'channels.read',
  'channels.manage',
  'outbox.read',
  'outbox.run',
  'monitoring.read',
  'monitoring.manage',
  'billing.read',
  'billing.manage',
  'roles.read',
  'roles.write',
  'members.read',
  'members.write',
  'api_keys.manage',
  'webhooks.manage',
  'audit.read',
  'audit.export',
  'policy.manage',
  'attachments.upload',
  'attachments.large',
  'messages.send',
];

export const LEGACY_ROLE_PERMISSION_MAP = {
  owner: [ALL_PERMISSIONS],
  super_admin: [ALL_PERMISSIONS],
  admin: [
    'inbox.read',
    'inbox.write',
    'contacts.read',
    'contacts.write',
    'contacts.merge',
    'routing.read',
    'routing.manage',
    'channels.read',
    'channels.manage',
    'outbox.read',
    'outbox.run',
    'monitoring.read',
    'monitoring.manage',
    'billing.read',
    'billing.manage',
    'roles.read',
    'roles.write',
    'members.read',
    'members.write',
    'api_keys.manage',
    'webhooks.manage',
    'audit.read',
    'audit.export',
    'policy.manage',
    'attachments.upload',
    'attachments.large',
    'messages.send',
  ],
  agent: [
    'inbox.read',
    'inbox.write',
    'contacts.read',
    'contacts.write',
    'contacts.merge',
    'outbox.read',
    'outbox.run',
    'monitoring.read',
    'channels.read',
    'attachments.upload',
    'messages.send',
  ],
  viewer: [
    'inbox.read',
    'contacts.read',
    'routing.read',
    'channels.read',
    'outbox.read',
    'monitoring.read',
    'billing.read',
    'roles.read',
    'members.read',
    'audit.read',
  ],
};
